### DISCUSSION TITLE
How to use versioned migrations with ent and atlas kubernetes operator?

### DISCUSSION THREAD

**Discussion by idc77** [ariga/atlas#2680] [Q&A]
I have this backend using ent.
Now I've been getting into kubernetes.
I have installed the Atlas Operator via helm as instructed in the readme.
```
kubectl apply -f https://raw.githubusercontent.com/ariga/atlas-operator/master/config/integration/databases/mysql.yaml
deployment.apps/mysql created
service/mysql created
secret/mysql-credentials created
```
I'm going to build an image of the backend with ent with [ko](https://github.com/ko-build/ko) and push to my private registry.
Next the deployment and service
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cooksbooks-backend
  labels:
    app: cooksbooks-backend
  namespace: cooksbooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cooksbooks-backend
  template:
    metadata:
      name: cooksbooks-backend
      namespace: cooksbooks
      labels:
        app: cooksbooks-backend
    spec:
      containers:
        - name: backend
          image: registry.icod.de/cooksbooks/backend/cooksbooks-1234567890bad8de8eeab40cd
          imagePullPolicy: Always
          command: [ cooksbooks ]
          args: [ "restful", "--bp=false", "--debug=false", "--addr=tcp::8080", "--dsn=mysql.default.svc.cluster.local:3306/cooksbooks" ]
          ports:
            - containerPort: 8080
              protocol: TCP
              name: backend-port
      imagePullSecrets:
        - name: registrycredentials
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cooksbooks-backend-service
  namespace: cooksbooks
spec:
  selector:
    app: cooksbooks-backend
  ports:
    - port: 8080
      protocol: TCP
      name: backend-svc-port
      targetPort: backend-port
```

Now how do I use the Atlas Operator to run the migrations first, please?
