### DISCUSSION TITLE
Using Atlas MySQL connector without docker access (inside a devcontainer) ... "docker://mysql/8/dev" ?

### DISCUSSION THREAD

**Discussion by michealroberts** [ariga/atlas#2987] [General]
As the title suggests, it's not clear or documented on how we connect without using docker. e.g., when working inside a devcontainer environment, setting up docker is neither a good idea or well established ...

**Comment by masseelch** [comment]
Hey. You need to ensure the container running atlas has access to the mysql container.

Usually you can specify the connection string by using the container name, e.g. mysql://user:pass@container-name:3306/database

**Reply by michealroberts** [reply]
I have tried a number of iterations, unfortunately. Do you have a clear example of how to achieve this?

Examples of errors I see:

`Error: mysql: query system variables: dial tcp: lookup atlas-demo on 198.19.248.200:53: no such host`

`Error: mysql: query system variables: dial tcp [::1]:3306: connect: connection refused`

It just really isn't clear ...

**Reply by masseelch** [reply]
Can you share a bit more about your setup, if the above isn't working? Where is this running?

**Reply by michealroberts** [reply]
I'm working inside a devcontainer. Atlas CLI tool is installed, but I do not have access to docker from inside said development container.

I've tried port forwarding, etc but nothing seems to work.

**Reply by giautm** [reply]
If you already run devcontainer, let try with this. It allow you run another container beside the devcontainer (the same network), then you can use the container name to connect to.

https://code.visualstudio.com/docs/devcontainers/create-dev-container#_use-docker-compose

**Reply by michealroberts** [reply]
This is the command I run to run the db from outside the devcontainer:

```
docker run --rm -d --name atlas-demo -p 3306:3306 -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_DATABASE=example mysql
```

Using:

```
data "external_schema" "gorm" {
  program = [
    "go",
    "run",
    "-mod=mod",
    "./loader",
  ]
}

env "gorm" {
  src = data.external_schema.gorm.url
  dev = "mysql://root:pass@:3306/example"
  migration {
    dir = "file://migrations"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}
```

And then running either one of these two commands from a Makefil:

```
#/*****************************************************************************************************************/

diff:
	atlas migrate diff --env gorm

#/*****************************************************************************************************************/

migrate:
	atlas schema apply \
  --url "mysql://root:pass@localhost:3306/numberstore-svc" \
  --to "file://migrations" \
  --dev-url "mysql://root:pass@localhost:3306/numberstore-svc" \
	--auto-approve

#/*****************************************************************************************************************/
```

Both fail with the same "`Error: mysql: query system variables: dial tcp [::1]:3306: connect: connection refused`" ...

**Reply by masseelch** [reply]
Can you try 127.0.0.1 instead of localhost?

**Reply by giautm** [reply]
@michealroberts I guess, the network of two containers are not the same. Please try to connect it to the same network. If you can ping from the devcontainer to the container ran from outside, atlas should work.

**Reply by michealroberts** [reply]
@giautm I'm just setting up and testing the idea of running a mysql instance alongside the devcontainer ...

**Reply by michealroberts** [reply]
I feel like I am close:

```
Error: mysql: query system variables: Error 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)
```

**Reply by michealroberts** [reply]
@giautm @masseelch This is my docker-compose file:

```yaml
services:

  development:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/numberstore-svc
    depends_on:
      - db
    env_file:
      - .env
    stdin_open: true
    network_mode: service:db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: numberstore-svc
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
```

And my atlas.hcl file:

```hcl
data "external_schema" "gorm" {
  program = [
    "go",
    "run",
    "-mod=mod",
    "./loader",
  ]
}

env "gorm" {
  src = data.external_schema.gorm.url
  dev = "mysql://root:pass@:3306/numberstore-svc"
  migration {
    dir = "file://migrations"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}
```
