### ISSUE TITLE
running migrations during test setup (using the go api)

### ISSUE THREAD

**Issue by bjornbyte** [ariga/atlas#1334]
Hello,

I'm just getting started with Atlas and overall found the documentation to be really great. I'm able to define a schema.hcl and generate version migrations and apply them to a local postgres database.  Everything is quite clear on the CLI side.

I want to also run the same migrations as part of my test setup; the ideal way to do this seems like it would be via the go api, however the documentation for the api seems relatively sparse.  Digging through the source code for the CLI it seems not so straightforward.  

what I would like to do in my test setup would be something like:
```golang
	db, err := sqlx.Connect("postgres", "user=postgres password=mypassword search_path=my_schema sslmode=disable")
	if err != nil {
		log.Fatalln(err)
	}

	driver, err := postgres.Open(db)  // this is "ariga.io/atlas/sql/postgres"
	runAtlasMigrate(driver, "file://db/migrations") //runs the migrations in 'db/migrations' using the given driver
``` 

is it possible to include a basic example of applying some existing migrations using the api in the api docs?

**Comment by rotemtam** [comment]
Hi @bjornbyte 

Thanks for reaching out, this is a great (and common) question. Let me answer you here, and I'll be sure to add a more detailed answer to the doc site soon. 

Atlas was built with the intention of being used in any language. While Atlas is written in Go and has public packages you can use to build applications, we recommend using it as a CLI binary to get the most out of it. This is the same way we consume Atlas ourselves here at @ariga. 

The question you ask touches on the general topic of how to write/run integration tests where schema migrations are involved. 

The common use case we see is:
* The database is provisioned outside of the test suite (using GitHub Actions services, docker-compose, or similar)
* Atlas is run to apply all existing migrations on this database prior to the tests running
* Integration tests are provided a connection string to the migrated, local database. 

In other cases, we even execute the Atlas binary programmatically (using `os.Exec` in Go, for example). 
Atlas contains a convenient `atlas schema clean` sub-command that is used to reset a specific db schema easily.

As an example, here's how you can use `docker-compose` to spin up a local MySQL container and use Atlas to apply migrations while its ready.

Suppose your directory structure is like this:
```
.
├── docker-compose.yaml
└── migrations
    ├── 20221207103204_init.sql
    └── atlas.sum

1 directory, 3 files
```
Your `docker-compose.yaml` will look like:
```yaml
version: "3.9"
services:
  migrate:
    image: arigaio/atlas:latest
    command: >
      migrate apply
      --url mysql://root:pass@mysql:3306/test
    networks:
      - db
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./migrations/:/migrations
  mysql:
    image: mysql:8.0.29
    platform: linux/amd64
    healthcheck:
      test: mysqladmin ping -ppass
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - db
networks:
  db:
```

**Comment by bjornbyte** [comment]
Hi @rotemtam,
thank you for the clarification and advice.  

I had started going down the `os.Exec` route yesterday after posting this, so given what you have said here I will likely continue down that path.

I had considered the docker compose approach as well, and do use it to start the db container before the test run. The trouble, for me, with that approach for running the migrations is that it makes it trickier to run my tests in parallel.  I'm currently achieving test isolation by giving each test its own sandbox (via separate schema), using the below function, but that requires that the migration be run on each schema, and since those are generated at runtime it can't be done with docker compose.

```
func createPostgresSandbox(t *testing.T) *sqlx.DB {
	db, err := sqlx.Connect("postgres", "user=postgres password=my_password sslmode=disable")
	if err != nil {
		log.Fatalln(err)
	}
	schemaName := generateTestScemaName()
	db.MustExec("CREATE SCHEMA " + schemaName)
	_ = db.Close()

	dataSource := fmt.Sprintf("user=postgres password=example search_path=%s sslmode=disable", schemaName)
	db, err = sqlx.Connect("postgres", dataSource)
	if err != nil {
		log.Fatalln(err)
	}

	return db
}
```

Perhaps there are other ways to achieve this, or maybe my tests don't need to run parallel, but that's my current use case in tests.  Thanks again for the guidance.

**Comment by bjornbyte** [comment]
in case it's useful to others, I ended up writing a small custom service to create databases on the fly for my tests, and run the migrations on them, then run that next to my database container with docker compose. Here are the relevant bits:

docker-compose.yml:
```yaml
# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"
    networks:
      - db
  sandbox_creator:
    build: ./db/testsetup
    volumes:
      - ./db/migrations/:/migrations
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
      PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - db
networks:
  db:
```

and the sandbox_creator Dockerfile
```dockerfile
FROM golang:latest as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN  GO111MODULE="on" CGO_ENABLED=0 GOOS=linux go build -o sandbox_creator .

FROM arigaio/atlas:latest
COPY --from=builder /app/sandbox_creator /
ENTRYPOINT ["/sandbox_creator"]
```

and the source for the helper service:
```golang
package main

import (
	"bytes"
	"database/sql"
	"fmt"
	"github.com/google/uuid"
	_ "github.com/lib/pq"
	"github.com/pkg/errors"
	"log"
	"net/http"
	"os"
	"os/exec"
	"strings"
)

func datasourceConnectionString(user string, password string, dbName string) string {
	return fmt.Sprintf("dbname=%s user=%s password=%s sslmode=disable host=postgres", dbName, user, password)
}

func generateSandboxName() string {
	return "sandbox_" + strings.ReplaceAll(uuid.NewString(), "-", "")[0:8]
}

func applyMigrations(user string, password string, dbName string) error {
	connectionString := fmt.Sprintf("postgres://%s:%s@postgres:5432/%s?sslmode=disable", user, password, dbName)
	cmd := exec.Command("/atlas", "migrate", "apply", "-u", connectionString)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	if err != nil {
		return errors.Wrap(err, stderr.String())
	}
	log.Printf("sdtout: %s", stdout.String())
	log.Printf("sderr: %s", stderr.String())
	return nil
}

func main() {
	password := os.Getenv("POSTGRES_PASSWORD")
	user := os.Getenv("POSTGRES_USER")
	defaultDbName := os.Getenv("POSTGRES_DB")
	port := os.Getenv("PORT")

	db, err := sql.Open("postgres", datasourceConnectionString(user, password, defaultDbName))
	if err != nil {
		log.Fatalln("failed to open db connection")
	}

	http.HandleFunc("/pgsandbox", func(w http.ResponseWriter, r *http.Request) {
		dbName := generateSandboxName()
		_, err := db.Exec(fmt.Sprintf("CREATE DATABASE %s;", dbName))
		if err != nil {
			log.Println(err)
			w.WriteHeader(500)
			w.Write([]byte(err.Error()))
			return
		}

		if err = applyMigrations(user, password, dbName); err != nil {
			log.Println(err)
			w.WriteHeader(500)
			w.Write([]byte(err.Error()))
			return
		}

		log.Println("created sandbox", dbName)
		fmt.Fprintf(w, datasourceConnectionString(user, password, dbName))
	})

	http.ListenAndServe(":"+port, nil)
}
```

Then my tests can do 
```golang
var sandboxClient = resty.New().SetBaseURL("http://localhost:8081")

	response, err := sandboxClient.NewRequest().Get("/pgsandbox")
	if err != nil {
		t.Fatal(err)
	}
	datasourceName := string(response.Body())
	datasourceName = strings.Replace(datasourceName, "host=postgres", "host=localhost", 1)
	db, err := sqlx.Connect("postgres", datasourceName)
```
and get a separate database with migrations applied.

Obviously room for some improvement here, like returning a json object from the /pgsandbox to avoid the hacky postgres/localhost host replacement, but it does the job nicely.
