### ISSUE TITLE
Error doing anything

### ISSUE THREAD

**Issue by amitavaghosh1** [ariga/atlas#1355]
```
version: "3.7"

services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql-seed-data:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${MYSQL_DB:?please provide a database}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "atlast_user", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 5

volumes:
  mysql-seed-data:
    driver: local
```

```
function generate_initial_schema() {
    DB="$1"
    SERVICE="$2"
    NAME="$3"

    dateSuffix=$(date -u '+%Y%m%d%H%M%S')
    parent_path=$(dirname "$0")
    
    docker run -d --name "${DB}" -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE="${DB}" mysql:8.0
    trap "docker stop ${DB}; docker rm ${DB}" EXIT

    # MYSQL_DB="${DB}" docker-compose -f infrafiles/mysql.docker-compose.yaml up -d 
    # trap "MYSQL_DB=${DB} docker-compose -f infrafiles/mysql.docker-compose.yaml down" EXIT   
    bash "$parent_path/wait-for-db.sh" 3306

    LOCAL_DB_URL="mysql://root:password@localhost:3306/$DB"

    REMOTE_DB_URL=$(get_remote_mysql_db_url "$DB")
    REMOTE_DB_URL=$(strip_tcp_from_url "$REMOTE_DB_URL")
    REMOTE_DB_URL="mysql://$REMOTE_DB_URL"

    echo "$LOCAL_DB_URL" 
    echo "$REMOTE_DB_URL" 

    FILENAME_PREX="migrations/${SERVICE}/${dateSuffix}_${NAME}"
    echo "generating table schema in ${FILENAME_PREX}.up.sql" 
    
    [[ ! -d  "migrations/${SERVICE}" ]] && mkdir -p "migrations/${SERVICE}"

    atlas schema diff --from "$LOCAL_DB_URL" --to "$REMOTE_DB_URL" > "${FILENAME_PREX}.up.sql"
    touch "${FILENAME_PREX}.down.sql"

    sed -i '' -E "s/\`${DB}\`\.//g" "${FILENAME_PREX}.up.sql"
    sed -i '' '/[^;] *$/s/$/;/' "${FILENAME_PREX}.up.sql"
}
```

Also sometimes I get,
```
generating table schema in migrations/clients/20221216124159_create_tables.up.sql
[mysql] 2022/12/16 18:12:02 packets.go:37: unexpected EOF
[mysql] 2022/12/16 18:12:02 packets.go:37: unexpected EOF
[mysql] 2022/12/16 18:12:02 packets.go:37: unexpected EOF
Error: mysql: query system variables: driver: bad connection
```
