### ISSUE TITLE
Pipeline support for SQL Server

### ISSUE THREAD

**Issue by jrmcpeek** [ariga/atlas#2037]
The SQL Server driver is in beta, so we must have an Atlas Cloud account and be logged in.

This works fine from a development environment perspective but doesn't seem to work for running in CI/CD, such as GitHub Actions.

I tried creating a bot and using that while passing the token in for atlas cloud, but it doesn't recognize that as an approved user for beta drivers.

Is there a way to do this, or is it only possible to perform manual migrations while the driver is in beta?

**Comment by masseelch** [comment]
Hey! I will have a look at this later today. Thanks for raising this.

**Comment by masseelch** [comment]
Hey @jrmcpeek, Atlas will now recognize bot tokens of a user having MSSQL enabled as well. Please note, that you have to pass the cloud token as `ATLAS_TOKEN` to the action so it will be picked up: 

```
- uses: ariga/atlas-action@v0
  env:
    ATLAS_TOKEN: ${{ secrets.<cloud-token> }} // required for the driver to be enabled
  with:
    cloud-token: ${{ secrets.<cloud-token> }} // required to report the run
```

I will clean up the API soon to remove the duplication of `ATLAS_TOKEN` and `cloud-token`. This was the fastest way to unblock you :-)
