### ISSUE TITLE
Github action fails with /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /atlas-action)

### ISSUE THREAD

**Issue by veqryn** [ariga/atlas#2300]
Trying to get atlas working for the first time as part of a github action that runs our tests.  It should set up the test db schema.

Github actions steps:
```
      - name: Set up Atlas DB Migrator
        uses: ariga/setup-atlas@v0

      - name: Atlas DB Migrator Version
        run: atlas version

      - name: Set up database
        uses: ariga/atlas-action/migrate/apply@v1
        with:
          url: mysql://root:@127.0.0.1:3306/myschema
          dir: file://sql/migrations
```

The github action container has, among other things, `gcc g++ libc6 cmake make git pkg-config` installed. (Tried with and without libc6)
Since the "setup-atlas" step was successful, I should hope the rest would work, but apparently not.

This results in:
```
Run ariga/setup-atlas@v0
Run curl -sSf https://atlasgo.sh | ATLAS_VERSION=latest CI=true sh
Downloading https://release.ariga.io/atlas/atlas-linux-amd64-latest
atlas version v0.15.1-bba752d-canary
https://github.com/ariga/atlas/releases/latest
Installation successful!

Run atlas version
atlas version v0.15.1-bba752d-canary
https://github.com/ariga/atlas/releases/latest

Run ariga/atlas-action/migrate/apply@v1
Using version v1
Downloading atlas-action binary: https://release.ariga.io/atlas-action/atlas-action-v1
/myrepo/atlas-action: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /myrepo/atlas-action)
/myrepo/atlas-action: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /myrepo/atlas-action)
Error: The process exited with code 1
```
