### ISSUE TITLE
Migrations files into Kubernetes ConfigMap

### ISSUE THREAD

**Issue by aaronkaz** [ariga/atlas#2326]
Greetings,
I'm looking for some direction as to how to get the contents of versioned migration files into a kubernetes config map yaml file.  There are some examples included [here](https://github.com/ariga/atlas-operator/tree/e78d6b242f56cc039d9bad883d8e9d8c2b92a923#getting-started) for versioned migrations that have the migration file contents and hash.  How exactly does one produce a file like this?

  ```yaml
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: migrationdir
  data:
    20230316085611.sql: |
      create sequence users_seq;
      create table users (
        id int not null default nextval ('users_seq'),
        name varchar(255) not null,
        email varchar(255) unique not null,
        short_bio varchar(255) not null,
        primary key (id)
      );
    atlas.sum: |
      h1:FwM0ApKo8xhcZFrSlpa6dYjvi0fnDPo/aZSzajtbHLc=
      20230316085611.sql h1:ldFr73m6ZQzNi8q9dVJsOU/ZHmkBo4Sax03AaL0VUUs=
  ``` 

Because the steps I'm familiar with are: 1) create migration file 2) calculate hash:
```$
atlas migrate new <name>
atlas migrate hash
```

When trying to insert the file contents into a helm template like this, I will get a `checksum mismatch` error:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-dir
data:
{{- $files := .Files }}
  {{ range $path, $_ :=  $files.Glob  "migrations/*.sql" }}
  {{ base $path }}: |-
{{ $files.Get $path | indent 4 }}
  {{- end }}
  atlas.sum: |-
{{ $files.Get "migrations/atlas.sum" | indent 4 }}
```
I would appreciate any help or recommendations on how to do this, thanks!

**Comment by aaronkaz** [comment]
For whoever it helps, I ended up getting this working with the following:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-dir
data:
{{- $files := .Files }}
{{- range $path, $_ :=  $files.Glob  "migrations/*.sql" }}
{{ base $path | indent 2 }}: |-
{{ $files.Get $path | indent 4 }}
{{- end }}
  atlas.sum: |-
{{ $files.Get "migrations/atlas.sum" | indent 4 }}
```
