### ISSUE TITLE
Can we integrate the atlas-operator and init container?

### ISSUE THREAD

**Issue by Amit-limbasiya** [ariga/atlas#2436]
I know what is init container and what atlas operator do.
But I want to know that is it possible (and recommended) to use the atlas operator in the init container.

What is the scenario I want to create?
There is a service in the kubernetes cluster and I want to introduce one init container which will just do migrations. I want to run in kubernetes cluster because it runs in one flow and inside cluster and it ensures that database is in the ready and expected state before the service starts. 
I want to know that Can I use the atlas operator inside the init containers? I have read the documentation related to [Deploying schema migrations to Kubernetes with Init Containers](https://atlasgo.io/guides/deploying/k8s-init-container).

Can anyone please tell me 
- when should I create init container and what will be the resources I have to create to apply the migration in the database before service starts 
- And when to use kubernetes operator and in this way what will be the workflow and is it beneficial in any way to automate the flow and put database in expected state before service starts?

**Comment by rotemtam** [comment]
Hi @Amit-limbasiya 

Kubernetes Operators are not meant to be used as init containers. They are supposed to be long-running processes that respond to changes in the CRDs that they manage. Running init containers is possible but not recommended - I would consider it an anti-pattern and advise you not to use it. If you're interested in some of the reasons behind this advice, view [this](https://youtu.be/K_Js7hzEyrA?si=op6JeTB27niK1G39) or [this](https://youtu.be/U-o4HUNGHsE?si=gHed7qLwWahwvzfe). 

The recommended path is: 

1. Run `atlas migrate push` to push the latest version of the migration directory to Atlas Cloud whenever you merge to your main branch (e.g. `master`). You can learn about this process in [GitOps for Databases Part 1](https://atlasgo.io/blog/2023/12/06/gitops-for-databases-part-1)
2. Run the Atlas Operator in your cluster as a long-running process. 
3. Create an `AtlasMigration` resource that points to your Atlas Cloud migration directory.

```
apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasMigration
metadata:
  name: migration
spec:
  urlFrom:
    secretKeyRef:
      key: url
      name: postgres-credentials
  cloud:
    project: "atlasdemo" # Atlas Cloud project name
    tokenFrom:
      secretKeyRef:
        name: atlas-credentials
        key: token
  dir:
    remote:
      name: "atlasdemo" # Migration directory name in your atlas cloud project
      tag: "1d579be616db48803bb21713fd836a9165030f18" # See below on how to obtain this value for your project.
```

4. When developers want to change the db version, update the tag to the new one in Atlas Cloud (by default, the git sha for the commit you're deploying).

Notice that it is highly recommended to make sure that the operator finishes running migrations *before* updating your application. This demonstrated using ArgoCD in [GitOps for Databases Part 2](https://atlasgo.io/blog/2023/12/11/gitops-for-databases-part-2). But can be done with Helm pre-upgrade hooks, FluxCD, and other options.  Please let me know if you need more guidance on that. 

### Running vs Atlas Cloud with an Init Container

If after all, you would like to deploy using an init container, this is my recommendation: 

1. Push the migration directory to Atlas Cloud (same as above) 
2. Follow the guide for [init containers](https://atlasgo.io/guides/deploying/k8s-init-container#adding-an-init-container) but instead of building a container with the migration files, you can use `arigaio/atlas:latest` and have your `atlas.hcl` file reference your cloud migration directory: 
```hcl
# The "local" environment represents our local testings.
atlas {
   cloud {
      token = "aci_..."
   }
}
env "k8s" {
  url = "postgres://postgres:pass@:5432/example?search_path=public&sslmode=disable"
  migration {
    dir = "atlas://app" # your cloud dir name
  }
}
```

HTH! Feel free to write back if something isn't clear.
