### ISSUE TITLE
Use SQL Server for the migration with atlas operator.

### ISSUE THREAD

**Issue by RajMarutitech** [ariga/atlas#2512]
How can I use the atlas operator for SQL Server to run the migration? 

- As when I use SQL server URL for the migration then it needs to do the atlas login before using the sqlserver driver so how can I add this step in the Kubernetes operator?

I have created the Atlas Cloud token.

How can I add this to validate it before running the migration?

I have created the AtlasMigration file it looks like this:

```
apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasMigration
metadata:
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: atlasmigration-sample
spec:
  urlFrom:
    secretKeyRef:
      name: pg-credentials-dev-env
      key: url
  cloud:
    tokenFrom: 
      secretKeyRef:
        name: token
        key: atlas-credentials
  dir:
    configMapRef:
      name: "migrations-dev-test-service" 
```

it still gives the error: **Error: login is required to use the 'sqlserver' beta driver. See: https://atlasgo.io/cloud/beta-drivers**

I am using GitOps to setup with ArgoCD to migrate can you please help me with this problem of how to avoid this error to run the successful migration?

**Comment by giautm** [comment]
Hello @RajMarutitech, we're working on the support for setting the ATLAS_TOKEN with atlas-operator ASAP. In the mean time, you can workaround by create patch the deployment of operator and add `ATLAS_TOKEN` environment variable on it.

**Comment by RajMarutitech** [comment]
@giautm please can you help me on how can i path the deployment of the operator and add the ATLAS_TOKEN environment variable on it?

And thanks for the reply.

**Comment by giautm** [comment]
> @giautm please can you help me on how can i patch the deployment of the operator and add the `ATLAS_TOKEN` environment variable on it?
> 
> And thanks for the reply.

Hello, you can run the bellow command for setting environment variable. Please notice that the environment variable can be remove after a new helm deploy.

```shell
kubectl set env deployment --namespace=default atlas-operator ATLAS_TOKEN=aci_xxx
```

**Comment by RajMarutitech** [comment]
I have updated the env variable with the above command but still i am getting the error: **Error: login is required to use the 'sqlserver' beta driver. See: https://atlasgo.io/cloud/beta-drivers**

by atlasMigration is same as above:

```
apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasMigration
metadata:
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: atlasmigration-sample
spec:
  urlFrom:
    secretKeyRef:
      name: pg-credentials-dev-env
      key: url
  cloud:
    tokenFrom: 
      secretKeyRef:
        name: token
        key: atlas-credentials
  dir:
    configMapRef:
      name: "migrations-dev-test-service" 

```


do i need to also change in this file?

i am using the ArgoCD for the migration and Atlas operator.
