### ISSUE TITLE
atlas-operator version 0.4.0 version not working for sql server driver

### ISSUE THREAD

**Issue by RajMarutitech** [ariga/atlas#2526]
I have updated my version of atlas-operator to 0.4.0 and i am using sql server driver for the database migration.

i have created the AtlasMigration controller and it looks like this:
```
apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasMigration
metadata:
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: atlasmigration-sample
spec:
  urlFrom:
    secretKeyRef:
      name: pg-credentials-dev-env
      key: url
  extraEnvs:
    - name: ATLAS_TOKEN
      valueFrom:
        secretKeyRef:
          name: token
          key: atlas-credentials
  dir:
    configMapRef:
      name: "migrations-dev-test-service"
```

but it gives me the error: **Error: login is required to use the 'sqlserver' beta driver. See: https://atlasgo.io/cloud/beta-drivers**

should i add the atlas token in the env variable with above specified code?

**Comment by datdao** [comment]
Hi @RajMarutitech, 'extraEnvs' only work though helm install

**Comment by giautm** [comment]
> Hello @datdao, Is there any way to provide the token to the atlas-operator so that i can avoid the error of: **login is required to use the 'sqlserver' beta driver. See: https://atlasgo.io/cloud/beta-drivers**

Hello @RajMarutitech, it depends on how you install our operator chart on k8s. If you install it via the helm terraform provider. You can pass the token / secret via `values`, like this:

```tf
resource "helm_release" "atlas-operator" {
  chart      = "atlas-operator"
  name       = "atlas-operator"
  repository = "oci://ghcr.io/ariga/charts"
  version    = "0.4.0"
  values = [
    yamlencode(
      extraEnvs = [
        {
          name  = "ATLAS_TOKEN"
          value = "aci_token" // Not recommended to hardcode the token
        },
        {
          // or use a secret
          name  = "ATLAS_TOKEN"
          valueFrom = {
            secretKeyRef = {
              name = "token"
              key  = "atlas-credentials"
            }
          }
        }
      ]
    )
  ]
}
```

or when you don't use the helm TF and install via helm, please create a `app_values.yaml` file, and run `helm install` with the file as input

```yaml app_values.yaml
extraEnvs:
  - name: ATLAS_TOKEN
    valueFrom:
      secretKeyRef:
        name: token
        key: atlas-credentials
```

Install chart with custom values:
```helm
helm install atlas-operator oci://ghcr.io/ariga/charts/atlas-operator -f app_values.yaml
```
