### ISSUE TITLE
Cannot use inspect in container

### ISSUE THREAD

**Issue by kantum** [ariga/atlas#2634]
I'm trying to do `atlas inspect --url <UR> --format '{{ sql . }}' > schema.sql` in a container but I cannot use the redirection as the official atlas docker image does not provide any shell. 🤷

This make the command way less interesting.

I basically want to always have a "latest" schema to work in development and be able to see the diff in git. Maybe I missed something that can do this already in the migrate command?

I'm wondering if an `--output schema.sql` options may be considered or if someone have figured out a better way to do this.

I will do a Dockerfile for now, but I feel dirty.

**Comment by kantum** [comment]
My Dockerfile to get a shell:
```Dockerfile
FROM golang:1.21 as build

RUN go install ariga.io/atlas/cmd/atlas@v0.13.1
```

My docker compose file:
```yaml
services:
  atlas-export-schema:
    image: my-atlas
    build: ./atlas
    volumes:
      - ${PWD}/atlas/vts/migrations:/migrations
      - ${PWD}/atlas/vts/schema.sql:/schema.sql
    command: /bin/bash -c "atlas schema inspect --url 'postgres://${POSTGRES_USER:?}:${POSTGRES_PASSWORD:?}@postgres:5432/vts?sslmode=disable' --format '{{ sql . \"    \" }}' > /schema.sql"
    depends_on:
      postgres:
        condition: service_healthy
```
This works, however, the output of `atlas schema inspect` is no idempotent, if I run it twice I get a different output. That's not what I need. I'm going to try with pg_dump now...
