### ISSUE TITLE
atlas-operator collation mismatch when using MariaDB

### ISSUE THREAD

**Issue by marc0777** [ariga/atlas#2817]
Hello,
I've been trying to use atlas-operator on k8s to handle migrations on a MariaDB database.

By default the operator tries to spin up a database instance as dev db. For MariaDB targets the instance created is MySQL, which uses the `utf8mb4_0900_ai_ci` collation, while our db instead uses `utf8mb4_general_ci`. The only way to make it work seems to be to explicitly set collation on the schema, and set `policy.diff.skip.modify_schema: true`.

Is this the expected behaviour, or am I missing something?

This is the configuration I've deployed on my cluster:
```yaml
apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: myapp
spec:
  urlFrom:
    secretKeyRef:
      key: url
      name: mysql-credentials
  schema:
    configMapKeyRef:
      key: schema.sql
      name: mysql-schema
  policy:
    lint:
      destructive:
        error: true
    diff:
      skip:
        drop_column: true
        modify_schema: true
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-schema
data:
  schema.sql: |
    create table users (
      id int not null auto_increment,
      name varchar(255) not null,
      email varchar(255) unique not null,
      short_bio varchar(255) not null,
      primary key (id)
    ) collate='utf8mb4_general_ci' charset='utf8mb4';
```

Thanks,
Marco
