### ISSUE TITLE
Running atlas commands against cockroachdb returns error with postgres wire protocol

### ISSUE THREAD

**Issue by theoriginalstove** [ariga/atlas#3031]
Running the commands `atlas migrate` or `atlas schema` when trying to create either declarative or versioned migration workflows will result in an error:
`Error: sql/migrate: taking database snapshot: query triggers: pq: unknown function: regexp_match()`

Steps to reproduce:
1. Setup a single node of Cockroachdb or cluster with docker compose (cluster setup with compose file below):

```yaml
# basic docker-compose.yaml to setup cockroachdb cluster locally.
# run docker compose up -d
# NOTE: once the cluster is started run the command:
# docker exec -it roach1 ./cockroach --host=roach1:26357 init --insecure
services:
  roach1:
    container_name: roach1
    image: cockroachdb/cockroach:latest-v23.2
    command: start --insecure --advertise-addr=roach1:26357 --http-addr=roach1:8080 --listen-addr=roach1:26357 --sql-addr=roach1:26257 --join=roach1:26357,roach2:26357,roach3:26357
    hostname: roach1
    networks:
      roachnet:
        aliases:
          - roach1
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - docker_data_cockroach1:/cockroach/cockroach-data
  roach2:
    container_name: roach2
    image: cockroachdb/cockroach:latest-v23.2
    command: start --advertise-addr=roach2:26357 --http-addr=roach2:8081 --listen-addr=roach2:26357 --sql-addr=roach2:26258 --insecure --join=roach1:26357,roach2:26357,roach3:26357   
    hostname: roach2
    networks:
      roachnet:
        aliases:
          - roach2
    ports:
      - "26258:26258"
      - "8081:8081"
    volumes:
      - docker_data_cockroach2:/cockroach/cockroach-data
  roach3:
    container_name: roach3
    image: cockroachdb/cockroach:latest-v23.2
    command: start --advertise-addr=roach3:26357 --http-addr=roach3:8082 --listen-addr=roach3:26357 --sql-addr=roach3:26259 --insecure --join=roach1:26357,roach2:26357,roach3:26357
    hostname: roach3
    networks:
      roachnet:
        aliases:
          - roach3
    ports:
      - "26259:26259"
      - "8082:8082"
    volumes:
      - docker_data_cockroach3:/cockroach/cockroach-data
networks:
  roachnet: 
    name: roachnet
volumes:
  docker_data_cockroach1: { }
  docker_data_cockroach2: { }
  docker_data_cockroach3: { }
```
2. Setup schema file `schemas.sql`:
```sql
CREATE TABLE IF NOT EXISTS "users" (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    PRIMARY KEY("id")
);
```
3. Run either command `atlas schema` or `atlas migrate`
```sh
atlas schema diff \
--from "postgres://root@localhost:26257/example1?sslmode=disable" \
--to "file://schemas.sql"
--dev-url "postgres://root@localhost:26257/defaultdb?sslmode=disable"
```

```sh
atlas migrate diff initial \
--to "file://schemas.sql" \
--dev-url "postgresql://root@localhost:26257?sslmode=disable" \
--format '{{ sql . " " }}'
```
