### ISSUE TITLE
Apply keeps suggesting the same changes

### ISSUE THREAD

**Issue by advdv** [ariga/atlas#3294]
I've been trying to get an schema into the hcl format:

```hcl
extension "citext" {}

schema "public" {}

//
// Functions
//

// a way to generated uuid following the v7 format, taken from (millisecond variant): 
// https://postgresql.verite.pro/blog/2024/07/15/uuid-v7-pure-sql.html
function "gen_random_uuidv7" {
  schema = schema.public
  lang   = SQL
  return = uuid
  as     = <<-SQL
 select encode(
   substring(int8send(floor(t_ms)::int8) from 3) ||
   int2send((7<<12)::int2 | ((t_ms-floor(t_ms))*4096)::int2) ||
   substring(uuid_send(gen_random_uuid()) from 9 for 8)
  , 'hex')::uuid
  from (select extract(epoch from clock_timestamp())*1000 as t_ms) s
  SQL
}

//
// domains
//
domain "email_address" {
  schema = schema.public
  type   = sql("citext")
  null   = true
  check "email_address_check" {
    expr = "(VALUE ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$')"
  }
  check "email_address_max_length" {
    expr = "(length(VALUE) < 300)"
  }
}

domain "text_standard" {
  schema = schema.public
  type   = varchar(300)
  null   = true
}

//
// tables
//

table "members" {
  schema = schema.public

  column "id" {
    type    = uuid
    default = sql("gen_random_uuidv7()")
  }

  column "primary_email" { type = domain.email_address }
  column "given_name" {
    type = domain.text_standard
    null = true
  }

  column "created_at" {
    type    = timestamptz
    default = sql("now()")
  }

  primary_key { columns = [column.id] }
}

table "organizations" {
  schema = schema.public
  column "id" {
    type    = uuid
    default = sql("gen_random_uuidv7()")
  }

  column "default_team_id" { type = uuid }

  primary_key { columns = [column.id] }

  foreign_key "default_team_fk" {
    columns     = [column.default_team_id]
    ref_columns = [table.teams.column.id]
    deferrable  = "INITIALLY_DEFERRED"
  }

  column "created_at" {
    type    = timestamptz
    default = sql("now()")
  }
}

table "teams" {
  schema = schema.public
  column "id" {
    type    = uuid
    default = sql("gen_random_uuidv7()")
  }

  column "organization_id" { type = uuid }

  primary_key { columns = [column.id] }
  foreign_key "organization_fk" {
    columns     = [column.organization_id]
    ref_columns = [table.organizations.column.id]
  }

  column "created_at" {
    type    = timestamptz
    default = sql("now()")
  }
}

table "team_members" {
  schema = schema.public
  column "member_id" { type = uuid }
  column "team_id" { type = uuid }
  primary_key { columns = [column.member_id, column.team_id] }

  foreign_key "member_fk" {
    columns     = [column.member_id]
    ref_columns = [table.members.column.id]
  }
  foreign_key "team_fk" {
    columns     = [column.team_id]
    ref_columns = [table.teams.column.id]
  }
}

//
// Policies
//

// we isolate all tables to the organization with row-level access control
policy "organization_isolation_select" {
  for_each = [table.teams]
  on       = each.value
  as       = RESTRICTIVE
  for      = SELECT
  using    = "(organization_id = NULLIF(current_setting('auth.user_organization_id', TRUE), '')::uuid)"
}
```

I then I run my apply command on an empty pg 17.2 database like so:  `atlas "schema" "apply" "--url" "postgresql://postgres:postgres@localhost:5442/postgres?sslmode=disable" "--to" "file://schema.hcl"` It will suggest the various create statements as i expect it to. 

But when i then run it again immediately it will suggest the following changes:

```
Planning migration statements (6 in total):

  -- modify "email_address" domain check constraint (drop old):
    -> ALTER DOMAIN "public"."email_address" DROP CONSTRAINT "email_address_check";
  -- modify "email_address" domain check constraint (add new):
    -> ALTER DOMAIN "public"."email_address" ADD CONSTRAINT "email_address_check" CHECK (VALUE ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$');
  -- modify "organization_isolation_select" policy:
    -> ALTER POLICY "organization_isolation_select" ON "public"."teams" USING (organization_id = NULLIF(current_setting('auth.user_organization_id', TRUE), '')::uuid);
  -- modify "members" table:
    -> ALTER TABLE "public"."members" ALTER COLUMN "id" SET DEFAULT gen_random_uuidv7();
  -- modify "organizations" table:
    -> ALTER TABLE "public"."organizations" ALTER COLUMN "id" SET DEFAULT gen_random_uuidv7();
  -- modify "teams" table:
    -> ALTER TABLE "public"."teams" ALTER COLUMN "id" SET DEFAULT gen_random_uuidv7();
```

If i keep running apply without changing anything to the schema it will always keep suggesting these changes. I understand that this should not be the case?

There is no atlas.hcl and my docker compose looks like this (if it matters):

```yaml
services:
  postgres:
    image: postgres:17.2-alpine
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command:
      - "postgres"
      - -c
      - wal_level=minimal # write even less to disk to speed up unit tests
      - -c
      - max_wal_senders=0 # write even less to disk to speed up unit tests
    tmpfs:
      - /var/lib/postgresql/data:rw # speeds up writing for testing
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-p", "5432"]
      interval: 1s
      timeout: 5s
      retries: 10
```
