### ISSUE TITLE
Dependency tree doesn't work for multiple Postgres functions with the same name

### ISSUE THREAD

**Issue by icopp** [ariga/atlas#3526]
To recreate, use a complex schema setup with multiple Postgres functions with the same name but with different arguments and dependencies. `atlas migrate diff` will then get confused about which is which, leading to errors that can only be worked around by including the dependencies of every function with the same name in the `depends_on` of all of those functions.

Instead of just tracking by name, it should be using the name and arguments, as the combination of those two things is what actually makes a function unique in Postgres.

**Comment by a8m** [comment]
Hey @icopp, are you getting this issue on the latest version? It was reported on Discord a while ago and should have been addressed.

If you're still experiencing it, could please share a minimal example to help us reproduce the issue?

**Comment by icopp** [comment]
> Hey [@icopp](https://github.com/icopp), are you getting this issue on the latest version? It was reported on Discord a while ago and should have been addressed.
> 
> If you're still experiencing it, could please share a minimal example to help us reproduce the issue?

Yes, this is on 0.34.0.

I don't have a minimal example to share, but this is using a composite schema setup with many (100+) files like:

```
data "composite_schema" "project" {
  schema {
    url = "file://project-hcl"
  }
  schema {
    url = "file://project-sql"
  }
}
```

with the function definitions with the same name (and all of their dependencies) split up between the different files.

**Comment by icopp** [comment]
Also, this wasn't an issue with 0.32.0, so it's some change between that version and 0.33 or 0.34.

**Comment by tjb9dc** [comment]
Hi — looks like a related regression has reappeared in the canary channel. Bisecting `atlas migrate diff` against `docker://postgres/17/dev`:

| atlas version                   | result   |
| ------------------------------- | -------- |
| `v1.2.0` (stable)               | ✅ pass  |
| `v1.2.1-a433759-canary` (May 5) | ✅ pass  |
| `v1.2.1-adb797e-canary` (May 6) | ❌ fail  |
| `v1.2.1-3e919c9-canary` (today) | ❌ fail  |

So the regression landed between `a433759` and `adb797e`.

### Minimal repro

`migrations/20260101000000_create_overloads.sql`:

```sql
CREATE OR REPLACE FUNCTION foo(n int)
    RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT 'int:' || n::text $$;

CREATE OR REPLACE FUNCTION foo(s text)
    RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT 'text:' || s $$;
```

`migrations/20260101000001_use_overload.sql`:

```sql
CREATE TABLE t (val text NOT NULL DEFAULT foo('hello'));
```

`schema.sql`:

```sql
CREATE TABLE t (val text NOT NULL);
```

Then `atlas migrate hash --dir file://migrations` and:

```
atlas migrate diff \
  --dir file://migrations \
  --to file://schema.sql \
  --dev-url 'docker://postgres/17/dev'
```

On `v1.2.0` this succeeds (generates `ALTER TABLE "public"."t" ALTER COLUMN "val" DROP DEFAULT`). On the current canary it fails with:

```
Error: sql/migrate: read migration directory state: sql/migrate: executing
statement "CREATE TABLE t (val text NOT NULL DEFAULT foo('hello'));" from
version "20260101000001": pq: function foo(unknown) does not exist at
column 43 (42883)
```

The function `foo(text)` exists in the previous migration, so the dev DB *should* have it when the second migration runs. The fact that postgres reports `foo(unknown)` not existing (rather than ambiguous-overload) suggests atlas is dropping or never applying one of the overloads to the dev DB during directory replay — consistent with the "tracking by name only" diagnosis in the original report.

**Comment by a8m** [comment]
@tjb9dc, do you use Atlas Pro? Asking to check how to reproduce this.

**Comment by tjb9dc** [comment]
> [@tjb9dc](https://github.com/tjb9dc), do you use Atlas Pro? Asking to check how to reproduce this.

Hey there!

No, we do not use Pro. Our GitHub Actions file looks like this

```yaml
  job:
    name: job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Atlas
        uses: ariga/setup-atlas@v0
        with:
          version: v1.2.0 # Note that adding the pin here has fixed it for us

      - name: Verify schema.hcl is in sync with migrations
        run: |
          atlas migrate diff \
            --dir file://src/ts/packages/foo/src/migrations \
            --to file://src/ts/packages/foo/src/schema.hcl \
            --dev-url 'docker://postgres/17/dev'
```
